import React, { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { Plus, X, Loader2, Save, Package, ClipboardList } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const AddData = () => {
  const [formData, setFormData] = useState({
    Name: "",
    ID: "",
    IPN: "",
    Description: "",
    Mfg: "",
    MFG_part_no: "",
    Package: "",
    Vendor_Id: "",
    Quantity: "",
    Avg_Price: "",
    Location: "",
    Status: "",
  });

  const [ComponentformData, setComponentFormData] = useState({
    label: "",
    name: "",
    description: "",
    type: "",
  });

  const [componentTypes, setComponentTypes] = useState([]);
  const [vendors, setVendors] = useState([]);
  const [isOpen, setIsOpen] = useState(false);
  const [isPartOpen, setPartIsOpen] = useState(false);
  const [selectedTableName, setSelectedTableName] = useState("");
  const [loading, setLoading] = useState(false);
  const [compLoading, setCompLoading] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  const navigate = useNavigate();

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        // Fetch vendors
        const vendorsResponse = await axios.get(
          "http://localhost:5000/api/vendors"
        );
        setVendors(vendorsResponse.data);

        // Fetch component types (table names)
        const componentsResponse = await axios.get(
          "http://localhost:5000/api/componentTypes"
        );
        setComponentTypes(componentsResponse.data);
      } catch (error) {
        console.error("Error fetching data:", error);
        setError("Failed to load data. Please refresh the page.");
      } finally {
        setLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleTableNameChange = (e) => {
    setSelectedTableName(e.target.value);
    setFormData({
      Name: "",
      ID: "",
      IPN: "",
      Description: "",
      Mfg: "",
      MFG_part_no: "",
      Package: "",
      Vendor_Id: "",
      Quantity: "",
      Avg_Price: "",
      Location: "",
      Status: "",
    });
    setError("");
  };

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleComponentChange = (e) => {
    const { name, value } = e.target;
    setComponentFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!selectedTableName) {
      setError("Please select a component type first");
      return;
    }

    setLoading(true);
    setError("");

    try {
      const response = await axios.post(
        `http://localhost:5000/api/sendVerificationEmailforPart`,
        {
          email: process.env.REACT_APP_AUTHOR_EMAIL,
          tableName: selectedTableName,
          formData: formData,
          emailSubjectPart: "Verify Data Addition in Inventory",
          emailHTMLPart: `<h6>Authorization generated for adding component parts to ${selectedTableName}</h6>
          <p>Please confirm the following data:</p>
          <p>Generated By: ${formData.Name}</p>
          <p>ID: ${formData.ID}</p>
          <p>IPN: ${formData.IPN}</p>
          <p>Description: ${formData.Description}</p>
          <p>Manufacturer: ${formData.Mfg}</p>
          <p>MFG_Part_Number: ${formData.MFG_part_no}</p>
          <p>Package: ${formData.Package}</p>
          <p>Vendor_ID: ${formData.Vendor_Id}</p>
          <p>Quantity: ${formData.Quantity}</p>
          <p>Avg_Price: ${formData.Avg_Price}</p>
          <p>Location: ${formData.Location}</p>
          <p>Status: ${formData.Status}</p>
          <p>Click the Button below to verify the component part submission:</p>`,
        },
        {
          headers: {
            "Content-Type": "application/json",
          },
        }
      );

      if (response.status === 200) {
        setSuccess(
          "Verification email sent! Click the link in your email to confirm submission."
        );
        setTimeout(() => {
          setSuccess("");
          setPartIsOpen(false);
          setFormData({
            Name: "",
            ID: "",
            IPN: "",
            Description: "",
            Mfg: "",
            MFG_part_no: "",
            Package: "",
            Vendor_Id: "",
            Quantity: "",
            Avg_Price: "",
            Location: "",
            Status: "",
          });
          navigate("/");
        }, 3000);
      }
    } catch (error) {
      console.error("Error adding data:", error);
      setError(
        error.response?.data?.error ||
          "Failed to add component. Please try again."
      );
    } finally {
      setLoading(false);
    }
  };

  const handleComponentSubmit = async (e) => {
    e.preventDefault();
    setCompLoading(true);
    setError("");

    try {
      const res = await axios.post(
        "http://localhost:5000/api/sendVerificationEmail",
        {
          email: process.env.REACT_APP_AUTHOR_EMAIL,
          formData: ComponentformData,
          emailSubjectComponent: "Component Submission Verification",
          emailHTMLComponent: `<p>A new component has been submitted for review.</p>
        <p>Component Details:</p>
        <p>Generated By: ${ComponentformData.label}</p>
        <p>Name: ${ComponentformData.name}</p>
        <p>Description: ${ComponentformData.description}</p>
        <p>Type: ${ComponentformData.type}</p>
        <p>Click the link below to verify your component submission:</p>`,
        }
      );

      if (res.status === 200) {
        setSuccess(
          "Verification email sent! Click the link in your email to confirm submission."
        );
        setTimeout(() => {
          setSuccess("");
          setIsOpen(false);
          setComponentFormData({
            label: "",
            name: "",
            description: "",
            type: "",
          });
        }, 3000);
      }
    } catch (error) {
      console.error("Error sending verification email:", error);
      setError("Failed to send verification email. Please try again.");
    } finally {
      setCompLoading(false);
    }
  };

  const renderFormField = (field) => {
    if (field === "Vendor_Id") {
      return (
        <motion.div
          className="space-y-2"
          key={field}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.3 }}
        >
          <label className="block text-sm font-medium text-gray-700">
            Vendor Name
          </label>
          <select
            name={field}
            value={formData[field]}
            onChange={handleChange}
            className="w-full px-4 py-2 bg-white border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 shadow-sm hover:border-blue-300"
            required
          >
            <option value="">Select Vendor</option>
            {vendors.map((vendor) => (
              <option key={vendor.Vendor_Id} value={vendor.Vendor_Id}>
                {vendor.Vendor_Name}
              </option>
            ))}
          </select>
        </motion.div>
      );
    }

    const getInputType = (field) => {
      if (["ID", "Quantity"].includes(field)) return "number";
      if (field === "Avg_Price") return "number";
      if (field === "Status") return "text";
      return "text";
    };

    return (
      <motion.div
        className="space-y-2"
        key={field}
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{
          duration: 0.3,
          delay: Object.keys(formData).indexOf(field) * 0.05,
        }}
      >
        <label className="block text-sm font-medium text-gray-700">
          {field.replace(/_/g, " ")}
        </label>
        <input
          type={getInputType(field)}
          name={field}
          value={formData[field]}
          onChange={handleChange}
          step={field === "Avg_Price" ? "0.01" : "1"}
          className="w-full px-4 py-2 bg-white border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-all duration-200 shadow-sm hover:border-blue-300"
          placeholder={`Enter ${field.replace(/_/g, " ").toLowerCase()}`}
          required
        />
      </motion.div>
    );
  };

  return (
    <div className="min-h-screen bg-fixed bg-gradient-to-b from-white to-gray-50 py-12 px-4 sm:px-6 lg:px-8 mt-16">
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="max-w-4xl mx-auto bg-white rounded-xl shadow-lg overflow-hidden"
      >
        <div className="px-6 py-8">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
            <motion.div
              className="flex-1 bg-white p-5 rounded-xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md"
              whileHover={{ y: -5 }}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="bg-blue-100 p-2 rounded-lg">
                    <Package className="w-6 h-6 text-blue-600" />
                  </div>
                  <div>
                    <h1 className="text-xl font-semibold text-gray-900">
                      Add Parts
                    </h1>
                    <p className="text-sm text-gray-500 mt-1">
                      Enter new parts in inventory
                    </p>
                  </div>
                </div>
                <motion.button
                  onClick={() => {
                    setPartIsOpen(!isPartOpen);
                    setIsOpen(false);
                    setSelectedTableName("");
                  }}
                  className="p-2 rounded-full bg-blue-50 hover:bg-blue-100 text-blue-600 transition-all duration-300"
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.95 }}
                >
                  {isPartOpen ? (
                    <X className="w-5 h-5" />
                  ) : (
                    <Plus className="w-5 h-5" />
                  )}
                </motion.button>
              </div>
            </motion.div>

            <motion.div
              className="flex-1 bg-white p-5 rounded-xl shadow-sm border border-gray-100 transition-all duration-300 hover:shadow-md"
              whileHover={{ y: -5 }}
            >
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="bg-indigo-100 p-2 rounded-lg">
                    <ClipboardList className="w-6 h-6 text-indigo-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-semibold text-gray-900">
                      Add Component
                    </h3>
                    <p className="text-sm text-gray-500 mt-1">
                      Create new component types
                    </p>
                  </div>
                </div>
                <motion.button
                  onClick={() => {
                    setIsOpen(!isOpen);
                    setPartIsOpen(false);
                    setSelectedTableName("");
                  }}
                  className="p-2 rounded-full bg-indigo-50 hover:bg-indigo-100 text-indigo-600 transition-all duration-300"
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.95 }}
                >
                  {isOpen ? (
                    <X className="w-5 h-5" />
                  ) : (
                    <Plus className="w-5 h-5" />
                  )}
                </motion.button>
              </div>
            </motion.div>
          </div>

          <AnimatePresence>
            {error && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="mt-6 px-4 py-3 bg-red-50 border border-red-200 text-red-700 rounded-lg flex items-center"
              >
                <svg
                  className="h-5 w-5 mr-2"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z"
                    clipRule="evenodd"
                  />
                </svg>
                {error}
              </motion.div>
            )}

            {success && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                className="mt-6 px-4 py-3 bg-green-50 border border-green-200 text-green-700 rounded-lg flex items-center"
              >
                <svg
                  className="h-5 w-5 mr-2"
                  viewBox="0 0 20 20"
                  fill="currentColor"
                >
                  <path
                    fillRule="evenodd"
                    d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z"
                    clipRule="evenodd"
                  />
                </svg>
                {success}
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {isOpen && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
              >
                <form
                  className="mt-6 space-y-6 bg-white p-6 rounded-xl shadow-sm border border-gray-100"
                  onSubmit={handleComponentSubmit}
                >
                  <h2 className="text-lg font-semibold text-gray-800 border-b pb-3">
                    Add New Component Type
                  </h2>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.1 }}
                    >
                      <label className="block mb-2 text-sm font-medium text-gray-700">
                        Generated By
                      </label>
                      <input
                        type="text"
                        name="label"
                        value={ComponentformData.label}
                        onChange={handleComponentChange}
                        placeholder="Enter your name"
                        className="w-full p-3 border border-gray-200 rounded-lg bg-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors duration-200"
                        required
                      />
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.2 }}
                    >
                      <label className="block mb-2 text-sm font-medium text-gray-700">
                        Component
                      </label>
                      <input
                        type="text"
                        name="name"
                        value={ComponentformData.name}
                        onChange={handleComponentChange}
                        placeholder="Enter component name"
                        className="w-full p-3 border border-gray-200 rounded-lg bg-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors duration-200"
                        required
                      />
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.3 }}
                      className="md:col-span-2"
                    >
                      <label className="block mb-2 text-sm font-medium text-gray-700">
                        Description
                      </label>
                      <textarea
                        name="description"
                        value={ComponentformData.description}
                        onChange={handleComponentChange}
                        placeholder="Enter description"
                        rows="3"
                        className="w-full p-3 border border-gray-200 rounded-lg bg-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors duration-200"
                        required
                      ></textarea>
                    </motion.div>
                    <motion.div
                      initial={{ opacity: 0, x: 20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.4 }}
                      className="md:col-span-2"
                    >
                      <label className="block mb-2 text-sm font-medium text-gray-700">
                        Type
                      </label>
                      <input
                        type="text"
                        name="type"
                        value={ComponentformData.type}
                        onChange={handleComponentChange}
                        placeholder="Enter type"
                        className="w-full p-3 border border-gray-200 rounded-lg bg-white shadow-sm focus:ring-2 focus:ring-indigo-500 focus:border-transparent transition-colors duration-200"
                        required
                      />
                    </motion.div>
                  </div>
                  <motion.button
                    type="submit"
                    className="w-full bg-indigo-600 text-white py-3 px-4 rounded-lg mt-4 hover:bg-indigo-700 flex justify-center items-center gap-2 transition-colors duration-300 shadow-sm"
                    whileHover={{ translateY: -2 }}
                    whileTap={{ scale: 0.98 }}
                    disabled={compLoading}
                  >
                    {compLoading ? (
                      <>
                        <Loader2 className="h-5 w-5 animate-spin" />
                        <span>Adding Component...</span>
                      </>
                    ) : (
                      <>
                        <Plus className="h-5 w-5" />
                        <span>Add Component</span>
                      </>
                    )}
                  </motion.button>
                </form>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {isPartOpen && (
              <motion.div
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: "auto" }}
                exit={{ opacity: 0, height: 0 }}
                transition={{ duration: 0.3 }}
                className="mt-8"
              >
                <label className="block text-sm font-medium text-gray-700">
                  Component Type
                </label>
                <select
                  value={selectedTableName}
                  onChange={handleTableNameChange}
                  className="mt-1 w-full px-4 py-3 bg-white border border-gray-200 rounded-lg shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-colors duration-200"
                >
                  <option value="">Select component type</option>
                  {componentTypes.map((type) => (
                    <option key={type.value} value={type.value}>
                      {type.label}
                    </option>
                  ))}
                </select>
              </motion.div>
            )}
          </AnimatePresence>

          <AnimatePresence>
            {selectedTableName && (
              <motion.form
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0, y: 30 }}
                transition={{ duration: 0.5 }}
                onSubmit={handleSubmit}
                className="mt-6 space-y-6 bg-white p-6 rounded-xl shadow-sm border border-gray-100"
              >
                <h2 className="text-lg font-semibold text-gray-800 border-b pb-3">
                  Add Part to {selectedTableName}
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  {Object.keys(formData).map((field) => renderFormField(field))}
                </div>

                <motion.button
                  type="submit"
                  disabled={loading}
                  className="w-full flex items-center justify-center px-4 py-3 bg-blue-600 text-white rounded-lg hover:bg-blue-700 focus:outline-none transition-colors duration-300 disabled:opacity-50 disabled:cursor-not-allowed shadow-sm"
                  whileHover={{ translateY: -2 }}
                  whileTap={{ scale: 0.98 }}
                >
                  {loading ? (
                    <>
                      <Loader2 className="animate-spin mr-2 h-5 w-5" />
                      Adding to Inventory...
                    </>
                  ) : (
                    <>
                      <Save className="mr-2 h-5 w-5" />
                      Add to Inventory
                    </>
                  )}
                </motion.button>
              </motion.form>
            )}
          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  );
};

export default AddData;
